### PR TITLE
Remove /discord if the invite link isn't valid

### PR DESCRIPTION
**Pull request by lumaa-dev**
Simple fork to not register the `/discord` command if the invite link does not start with https://discord.gg or with https://discord.com/invite

### CODE REVIEW

**Comment by onebeastchris** [comment]
Hey! Thanks for the PR. While I like the option to not register the command, this way of checking will break all shortened links - some people might put a link that forwards one to a discord link.
Instead, I'd propose a simple config option whether to enable the command?

Thanks for the contribution ❤️

**Comment by onebeastchris** [comment]
Alternatively; we could just check if the value *isn't* the default one and then don't register it. Might be cleaner.

**Comment by lumaa-dev** [comment]
Both the solutions you give seem good.

**Comment by onebeastchris** [comment]
I like this more; but you can remove the second check for whether the command is enabled - it's already checked in line 20, just above the new check

**Comment by lumaa-dev** [comment]
It should be good now, thanks for giving me the necessary instructions 👍

**Review by onebeastchris — APPROVED** [review]

**Pull request merged**
